 
; bits for variable sflag_event
#define  sh1         0                   ; place holder
#define  sh2         1                   ; place holder
#define  sh3         2                   ; place holder
#define  sh4         3                   ; place holder
#define  sh5         4                   ; place holder
#define  sh6         5                   ; place holder
#define  sh7         6                   ; place holder
#define  rw_done     7                   ; flag bit


; bits for variable eflag_event
#define  ack_error   0                   ; flag bit
#define  eh1         1                   ; place holder
#define  eh2         2                   ; place holder
#define  eh3         3                   ; place holder
#define  eh4         4                   ; place holder
#define  eh5         5                   ; place holder
#define  eh6         6                   ; place holder
#define  eh7         7                   ; place holder
